apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: myns
  name: flask-deployment
  labels:
    app: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: flask-app
        image: 140744541048.dkr.ecr.us-east-1.amazonaws.com/myreg:myapp
        envFrom:
          - configMapRef:
             name: mysql-configmap
        ports:
        - containerPort: 5002
        
        readinessProbe:
            initialDelaySeconds: 35
            periodSeconds: 20
            httpGet:
              port: 5002
              path: /

        livenessProbe:
            initialDelaySeconds: 35
            periodSeconds: 20
            httpGet:
              port: 5002
              path: /
