

pipeline {
   agent any
    parameters {
        string(name: 'access', description: 'aws access key')
        string(name: 'secret', description: 'aws secret key')
    }
   stages {
      
      
      stage('configure aws and access eks cluster') {
         steps {
            script {
          sh "aws configure set aws_access_key_id ${params.access} && aws configure set aws_secret_access_key ${params.secret}"
          sh "aws eks --region us-east-1 update-kubeconfig --name my-cluster"
        
         }
         }
      }
      
      stage('deploy kubernates files') {
         steps {
            script {
          sh "kubectl apply -f ns.yml"
          sh "kubectl apply -f pv.yml"
          sh "kubectl apply -f services.yml"
          sh "kubectl apply -f config.yml"
          sh "kubectl apply -f statfulset.yml"
          sh "kubectl apply -f deploy.yml"
          sh "kubectl apply -f ingress.yml"
        
         }
         }
      }
      
      
      
   }
}
